name: wordle-hook

on:
  schedule:
    # Run @ 9:00 AM PST (17:00 UTC) everyday
    - cron: "0 17 * * *"

jobs:
  wordle-hook:
    runs-on: ubuntu-latest
    name: Run Wordle hook
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs v14 & npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Run wordle hook
        run: npm start
